server:
  port: 8081

spring:
  application:
    name: tms-rest-adapter

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true

# Feign clients
feign:
  client:
    config:
      tms-config-service:
        url: ${CONFIG_SERVICE_URL:http://localhost:8086}
        read-timeout: 10000
        connect-timeout: 5000

# WireMock configuration (simulates external partner APIs)
wiremock:
  enabled: ${WIREMOCK_ENABLED:true}
  port: 8089
  base-url: http://localhost:8089

# Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.tms.adapter: INFO
    org.springframework.web.client: WARN